format = """
[](#001628)\
$directory\
[](fg:#001628 bg:#C8102E)\
[](fg:#C8102E bg:#99D9D9)\
$git_branch\
$git_status\
[ ](fg:#99D9D9)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[directory]
style = "bg:#001628"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"midgard" = "🌍"
"packages" = "📦"

[git_branch]
symbol = ""
style = "bg:#99D9D9"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#99D9D9"
format = '[$all_status$ahead_behind ]($style)'
